# Generated by Django 5.2.1 on 2026-07-28 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_security_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttoken",
            name="last_used_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
