version = 5.7.0
archive_dir = /etc/letsencrypt/archive/bazikhooneh.codelighthouse.ir
cert = /etc/letsencrypt/live/bazikhooneh.codelighthouse.ir/cert.pem
privkey = /etc/letsencrypt/live/bazikhooneh.codelighthouse.ir/privkey.pem
chain = /etc/letsencrypt/live/bazikhooneh.codelighthouse.ir/chain.pem
fullchain = /etc/letsencrypt/live/bazikhooneh.codelighthouse.ir/fullchain.pem

[renewalparams]
account = aedfa29cce0897550178b793ce491ed7
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
webroot_path = /var/www/letsencrypt,

[[webroot_map]]
bazikhooneh.codelighthouse.ir = /var/www/letsencrypt
