package ir.codelighthouse.bazikhooneh.account;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.Build;
import ir.codelighthouse.bazikhooneh.*;import org.json.*;
public final class NotificationSync{
 private static final String CHANNEL="social";private NotificationSync(){}
 public static void refresh(Activity activity){SessionStore store=new SessionStore(activity);if(!store.isSignedIn()||!activity.getSharedPreferences(SettingsActivity.PREFS,Activity.MODE_PRIVATE).getBoolean(SettingsActivity.NOTIFICATIONS,true))return;
  if(Build.VERSION.SDK_INT>=33&&activity.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){activity.requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},41);return;}
  new AccountManagementClient(BuildConfig.API_BASE_URL,store.token(),new AccountManagementClient.Listener(){public void onSuccess(String op,JSONObject json){activity.runOnUiThread(()->showNewest(activity,json));}public void onError(String error){}}).get("notifications","/api/v1/accounts/notifications/");}
 private static void showNewest(Activity activity,JSONObject json){JSONArray values=json.optJSONArray("results");if(values==null||values.length()==0)return;JSONObject item=values.optJSONObject(0);long id=item.optLong("id");android.content.SharedPreferences prefs=activity.getSharedPreferences("notification_state",Activity.MODE_PRIVATE);if(id<=prefs.getLong("last_id",0))return;prefs.edit().putLong("last_id",id).apply();NotificationManager manager=(NotificationManager)activity.getSystemService(Context.NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26)manager.createNotificationChannel(new NotificationChannel(CHANNEL,activity.getString(R.string.notifications_title),NotificationManager.IMPORTANCE_DEFAULT));String kind=item.optString("kind");Class<?> destination=("friend_request".equals(kind)||"game_invite".equals(kind))?FriendsActivity.class:NotificationsActivity.class;Intent intent=new Intent(activity,destination);JSONObject data=item.optJSONObject("data");if(data!=null&&data.has("room_code"))intent.putExtra("room_code",data.optString("room_code"));PendingIntent target=PendingIntent.getActivity(activity,(int)(id%Integer.MAX_VALUE),intent,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder builder=Build.VERSION.SDK_INT>=26?new Notification.Builder(activity,CHANNEL):new Notification.Builder(activity);manager.notify((int)(id%Integer.MAX_VALUE),builder.setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle(item.optString("title")).setContentText(item.optString("body")).setContentIntent(target).setAutoCancel(true).build());}
}
