package ir.codelighthouse.bazikhooneh;
import android.content.Intent;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;import org.json.*;import ir.codelighthouse.bazikhooneh.account.*;import ir.codelighthouse.bazikhooneh.game.ludo.*;import ir.codelighthouse.bazikhooneh.online.LudoOnlineClient;
public final class LudoOnlineActivity extends NavigableActivity{
 private final Handler handler=new Handler(Looper.getMainLooper());private LudoOnlineClient client;private String room,token,host;private int ownColor,lastVersion=-1;private boolean destroyed;private LudoGame game;private LudoBoardView board;private LinearLayout actions,summary;private TextView status,roomInfo;private JSONArray seats;
 @Override protected void onCreate(Bundle state){super.onCreate(state);setContentView(R.layout.activity_ludo);findViewById(R.id.ludo_online_controls).setVisibility(View.VISIBLE);board=findViewById(R.id.ludo_board);actions=findViewById(R.id.ludo_piece_actions);status=findViewById(R.id.ludo_status);summary=findViewById(R.id.ludo_summary);roomInfo=findViewById(R.id.ludo_room_info);android.content.SharedPreferences prefs=getSharedPreferences("ludo_online",MODE_PRIVATE);room=prefs.getString("room","");token=prefs.getString("token","");ownColor=prefs.getInt("color",0);host=prefs.getString("host","");SessionStore store=new SessionStore(this);client=new LudoOnlineClient(BuildConfig.API_BASE_URL,store.token(),listener);findViewById(R.id.ludo_roll).setOnClickListener(v->client.roll());findViewById(R.id.ludo_start_with_bots).setOnClickListener(v->client.start(room));findViewById(R.id.ludo_share_room).setOnClickListener(v->startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,getString(R.string.ludo_share_text,room)),getString(R.string.share_room))));client.reconnect(room,token);}
 private void render(JSONObject value){seats=value.optJSONArray("seats");int version=value.optInt("version");boolean waiting="waiting".equals(value.optString("room_state"));if(!waiting&&game!=null&&version==lastVersion)return;roomInfo.setText(getString(R.string.ludo_online_room_info,room,seatsDescription()));findViewById(R.id.ludo_start_with_bots).setVisibility(waiting&&new SessionStore(this).username().equals(host)?View.VISIBLE:View.GONE);findViewById(R.id.ludo_roll).setVisibility(waiting?View.GONE:View.VISIBLE);if(waiting){status.setText(R.string.ludo_waiting_players);board.setVisibility(View.GONE);renderWaitingCards();if(lastVersion<0)announce(status.getText().toString());lastVersion=version;return;}board.setVisibility(View.VISIBLE);JSONObject state=value.optJSONObject("game");game=parse(state);List<Integer> legal=game.currentPlayer()==ownColor?game.legalPieces():Collections.emptyList();board.bind(game,legal,client::move);actions.removeAllViews();boolean turn=game.currentPlayer()==ownColor;findViewById(R.id.ludo_roll).setEnabled(turn&&game.awaitingRoll());String current=game.winner()>=0?getString(R.string.ludo_winner,playerLabel(game.winner())):turn?(game.awaitingRoll()?getString(R.string.ludo_online_your_roll):getString(R.string.ludo_choose_piece,playerLabel(ownColor),game.die())):getString(R.string.ludo_online_other_turn,playerLabel(game.currentPlayer()));status.setText(current);for(int piece:legal){Button button=new Button(this);button.setText(getString(R.string.ludo_piece_action,piece+1,position(game.progress(ownColor,piece))));int selected=piece;button.setOnClickListener(v->client.move(selected));actions.addView(button);}renderGameCards();if(lastVersion>=0&&version>lastVersion)announceEvents(state.optJSONArray("events"),current);else if(lastVersion<0)announce(current);lastVersion=version;}
 private void announceEvents(JSONArray events,String current){StringBuilder text=new StringBuilder();for(int i=0;events!=null&&i<events.length();i++){JSONObject event=events.optJSONObject(i);int player=event.optInt("player");String message;if("roll".equals(event.optString("kind")))message=getString(R.string.ludo_roll_announcement,playerLabel(player),event.optInt("die"));else{message=getString(R.string.ludo_move_announcement,playerLabel(player),event.optInt("piece")+1,position(event.optInt("to")));JSONArray captured=event.optJSONArray("captured");if(captured!=null&&captured.length()>0)message+=" "+getString(R.string.ludo_capture_announcement,captured.length());}if(text.length()>0)text.append(". ");text.append(message);}if(text.length()>0)text.append(". ");text.append(current);announce(text.toString());}private void announce(String text){status.announceForAccessibility(text);}
 private LudoGame parse(JSONObject state){int[][] positions=new int[4][4];boolean[] active=new boolean[4],bots=new boolean[4];JSONArray rows=state.optJSONArray("positions"),a=state.optJSONArray("active"),b=state.optJSONArray("bots");for(int p=0;p<4;p++){active[p]=a.optBoolean(p);bots[p]=b.optBoolean(p);JSONArray row=rows.optJSONArray(p);for(int i=0;i<4;i++)positions[p][i]=row.optInt(i,-1);}return LudoGame.snapshot(positions,active,bots,state.optInt("current_player"),state.optInt("die"),state.optBoolean("awaiting_roll"),state.optInt("winner",-1),state.optInt("consecutive_sixes"),state.optBoolean("third_six_penalty"));}
 private void renderWaitingCards(){summary.removeAllViews();for(int i=0;seats!=null&&i<seats.length();i++){JSONObject seat=seats.optJSONObject(i);addCard(getString(R.string.ludo_waiting_player_summary,seat.optString("display_name"),seat.optInt("color")+1,color(seat.optInt("color"))));}}
 private void renderGameCards(){summary.removeAllViews();for(int p=0;p<4;p++)if(game.isActive(p)){StringBuilder pieces=new StringBuilder();for(int i=0;i<4;i++){if(i>0)pieces.append(", ");pieces.append(position(game.progress(p,i)));}addCard(getString(R.string.ludo_player_summary,displayName(p),p+1,pieces));}}
 private void addCard(String text){TextView card=new TextView(this);card.setText(text);card.setTextSize(17);card.setPadding(24,20,24,20);card.setBackgroundColor(getColor(R.color.surface));LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);params.bottomMargin=12;summary.addView(card,params);}
 private String seatsDescription(){StringBuilder text=new StringBuilder();for(int i=0;seats!=null&&i<seats.length();i++){JSONObject seat=seats.optJSONObject(i);if(i>0)text.append('\n');text.append(seat.optString("display_name")).append(" — ").append(color(seat.optInt("color")));}return text.toString();}
 private String displayName(int player){for(int i=0;seats!=null&&i<seats.length();i++){JSONObject seat=seats.optJSONObject(i);if(seat.optInt("color")==player)return seat.optString("display_name");}return color(player);}private String playerLabel(int player){return getString(R.string.ludo_named_player,displayName(player),player+1,color(player));}private String color(int p){int[] ids={R.string.ludo_red,R.string.ludo_blue,R.string.ludo_green,R.string.ludo_yellow};return getString(ids[Math.max(0,Math.min(3,p))]);}private String position(int v){return v<0?getString(R.string.ludo_at_home):v==57?getString(R.string.ludo_finished):v>=52?getString(R.string.ludo_final_lane,v-51):getString(R.string.ludo_track_position,v+1);}
 private final LudoOnlineClient.Listener listener=new LudoOnlineClient.Listener(){public void onSession(JSONObject s){}public void onState(JSONObject state){runOnUiThread(()->render(state));}public void onError(String error){runOnUiThread(()->{String message=AccountErrorMessages.get(LudoOnlineActivity.this,error);status.setText(message);announce(message);});}public void onDisconnected(){runOnUiThread(()->{if(destroyed)return;status.setText(R.string.online_disconnected);announce(status.getText().toString());handler.postDelayed(()->{if(!destroyed)client.reconnect(room,token);},2000);});}};
 @Override protected void onDestroy(){destroyed=true;handler.removeCallbacksAndMessages(null);client.disconnect();super.onDestroy();}
}
