package ir.codelighthouse.bazikhooneh;
import android.content.Intent;import android.os.*;import android.view.View;import android.widget.*;import java.util.*;import org.json.*;import ir.codelighthouse.bazikhooneh.account.*;import ir.codelighthouse.bazikhooneh.game.ludo.*;import ir.codelighthouse.bazikhooneh.online.LudoOnlineClient;
public final class LudoOnlineActivity extends NavigableActivity{private LudoOnlineClient client;private String room,token,host;private int ownColor;private LudoGame game;private LudoBoardView board;private LinearLayout actions;private TextView status,summary,roomInfo;private JSONObject payload;
 @Override protected void onCreate(Bundle state){super.onCreate(state);setContentView(R.layout.activity_ludo);findViewById(R.id.ludo_online_controls).setVisibility(View.VISIBLE);board=findViewById(R.id.ludo_board);actions=findViewById(R.id.ludo_piece_actions);status=findViewById(R.id.ludo_status);summary=findViewById(R.id.ludo_summary);roomInfo=findViewById(R.id.ludo_room_info);android.content.SharedPreferences prefs=getSharedPreferences("ludo_online",MODE_PRIVATE);room=prefs.getString("room","");token=prefs.getString("token","");ownColor=prefs.getInt("color",0);host=prefs.getString("host","");SessionStore store=new SessionStore(this);client=new LudoOnlineClient(BuildConfig.API_BASE_URL,store.token(),listener);findViewById(R.id.ludo_roll).setOnClickListener(v->client.roll());findViewById(R.id.ludo_start_with_bots).setOnClickListener(v->client.start(room));findViewById(R.id.ludo_share_room).setOnClickListener(v->startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,getString(R.string.ludo_share_text,room)),getString(R.string.share_room))));client.reconnect(room,token);}
 private void render(JSONObject value){payload=value;String roomState=value.optString("room_state");roomInfo.setText(getString(R.string.ludo_online_room_info,room,seatsDescription(value.optJSONArray("seats"))));boolean waiting="waiting".equals(roomState);findViewById(R.id.ludo_start_with_bots).setVisibility(waiting&&new SessionStore(this).username().equals(host)?View.VISIBLE:View.GONE);findViewById(R.id.ludo_roll).setVisibility(waiting?View.GONE:View.VISIBLE);if(waiting){status.setText(R.string.ludo_waiting_players);board.setVisibility(View.GONE);return;}board.setVisibility(View.VISIBLE);JSONObject state=value.optJSONObject("game");game=parse(state);List<Integer> legal=game.currentPlayer()==ownColor?game.legalPieces():Collections.emptyList();board.bind(game,legal,client::move);actions.removeAllViews();boolean turn=game.currentPlayer()==ownColor;findViewById(R.id.ludo_roll).setEnabled(turn&&game.awaitingRoll());status.setText(game.winner()>=0?getString(R.string.ludo_winner,color(game.winner())):turn?(game.awaitingRoll()?getString(R.string.ludo_online_your_roll):getString(R.string.ludo_choose_piece,color(ownColor),game.die())):getString(R.string.ludo_online_other_turn,color(game.currentPlayer())));for(int piece:legal){Button button=new Button(this);button.setText(getString(R.string.ludo_piece_action,piece+1,position(game.progress(ownColor,piece))));int selected=piece;button.setOnClickListener(v->client.move(selected));actions.addView(button);}summary.setText(seatsDescription(value.optJSONArray("seats")));status.announceForAccessibility(status.getText());}
 private LudoGame parse(JSONObject state){int[][] positions=new int[4][4];boolean[] active=new boolean[4],bots=new boolean[4];JSONArray rows=state.optJSONArray("positions"),a=state.optJSONArray("active"),b=state.optJSONArray("bots");for(int p=0;p<4;p++){active[p]=a.optBoolean(p);bots[p]=b.optBoolean(p);JSONArray row=rows.optJSONArray(p);for(int i=0;i<4;i++)positions[p][i]=row.optInt(i,-1);}return LudoGame.snapshot(positions,active,bots,state.optInt("current_player"),state.optInt("die"),state.optBoolean("awaiting_roll"),state.optInt("winner",-1));}
 private String seatsDescription(JSONArray seats){StringBuilder text=new StringBuilder();for(int i=0;seats!=null&&i<seats.length();i++){JSONObject seat=seats.optJSONObject(i);if(text.length()>0)text.append("، ");text.append(color(seat.optInt("color"))).append(": ").append(seat.optString("display_name"));}return text.toString();}
 private String color(int p){int[] ids={R.string.ludo_red,R.string.ludo_blue,R.string.ludo_green,R.string.ludo_yellow};return getString(ids[p]);}private String position(int v){return v<0?getString(R.string.ludo_at_home):v==57?getString(R.string.ludo_finished):v>=52?getString(R.string.ludo_final_lane,v-51):getString(R.string.ludo_track_position,v+1);}
 private final LudoOnlineClient.Listener listener=new LudoOnlineClient.Listener(){public void onSession(JSONObject s){}public void onState(JSONObject state){runOnUiThread(()->render(state));}public void onError(String error){runOnUiThread(()->status.setText(AccountErrorMessages.get(LudoOnlineActivity.this,error)));}public void onDisconnected(){runOnUiThread(()->{status.setText(R.string.online_disconnected);new Handler(Looper.getMainLooper()).postDelayed(()->client.reconnect(room,token),2000);});}};
 @Override protected void onDestroy(){client.disconnect();super.onDestroy();}
}
