package ir.codelighthouse.bazikhooneh;
import android.app.AlertDialog;import android.os.Bundle;import android.view.View;import android.widget.*;import ir.codelighthouse.bazikhooneh.account.*;import org.json.*;import java.time.*;import java.time.format.*;
public final class SessionsActivity extends NavigableActivity{private AccountManagementClient client;private TextView status;private LinearLayout list;
 @Override protected void onCreate(Bundle state){super.onCreate(state);setContentView(R.layout.activity_sessions);SessionStore store=new SessionStore(this);client=new AccountManagementClient(BuildConfig.API_BASE_URL,store.token(),listener);status=findViewById(R.id.sessions_status);list=findViewById(R.id.sessions_list);findViewById(R.id.revoke_sessions).setOnClickListener(v->confirmRevoke());findViewById(R.id.sessions_retry).setOnClickListener(v->load());load();}
 private void confirmRevoke(){new AlertDialog.Builder(this).setTitle(R.string.revoke_other_sessions).setMessage(R.string.revoke_sessions_confirmation).setNegativeButton(R.string.cancel_action,null).setPositiveButton(R.string.confirm_action,(d,w)->client.delete("revoke","/api/v1/accounts/sessions/")).show();}
 private void load(){findViewById(R.id.sessions_loading).setVisibility(View.VISIBLE);findViewById(R.id.sessions_retry).setVisibility(View.GONE);client.get("list","/api/v1/accounts/sessions/");}
 private String date(String raw){try{return DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm").withZone(ZoneId.systemDefault()).format(Instant.parse(raw));}catch(Exception e){return raw;}}
 private final AccountManagementClient.Listener listener=new AccountManagementClient.Listener(){public void onSuccess(String op,JSONObject json){runOnUiThread(()->{if("list".equals(op)){findViewById(R.id.sessions_loading).setVisibility(View.GONE);list.removeAllViews();JSONArray results=json.optJSONArray("results");status.setText(getString(R.string.active_sessions_count,results==null?0:results.length()));for(int i=0;results!=null&&i<results.length();i++){JSONObject session=results.optJSONObject(i);TextView item=new TextView(SessionsActivity.this);item.setText(getString(session.optBoolean("current")?R.string.current_session_item:R.string.other_session_item,date(session.optString("created_at")),date(session.optString("last_used_at"))));item.setTextSize(17);item.setPadding(0,16,0,16);list.addView(item);}}else{status.setText(R.string.other_sessions_revoked);load();}});}public void onError(String error){runOnUiThread(()->{findViewById(R.id.sessions_loading).setVisibility(View.GONE);findViewById(R.id.sessions_retry).setVisibility(View.VISIBLE);status.setText(AccountErrorMessages.get(SessionsActivity.this,error));});}};
}
