package ir.codelighthouse.bazikhooneh.online;
import java.io.IOException;import okhttp3.*;import org.json.*;
public final class LudoOnlineClient{
 public interface Listener{void onSession(JSONObject session);void onState(JSONObject state);void onError(String error);void onDisconnected();}
 private static final MediaType JSON=MediaType.get("application/json; charset=utf-8");private final OkHttpClient http=new OkHttpClient();private final String base;private final String accountToken;private final Listener listener;private WebSocket socket;private boolean closing;
 public LudoOnlineClient(String base,String accountToken,Listener listener){this.base=base.endsWith("/")?base.substring(0,base.length()-1):base;this.accountToken=accountToken;this.listener=listener;}
 public void create(){post("/api/v1/ludo/rooms/",new JSONObject());}public void join(String code){try{post("/api/v1/ludo/rooms/join/",new JSONObject().put("code",code));}catch(JSONException ignored){}}
 public void start(String code){post("/api/v1/ludo/rooms/"+code+"/start/",new JSONObject());}
 private void post(String path,JSONObject body){Request request=new Request.Builder().url(base+path).header("Authorization","Bearer "+accountToken).post(RequestBody.create(body.toString(),JSON)).build();http.newCall(request).enqueue(new Callback(){public void onFailure(Call c,IOException e){listener.onError("connection_failed");}public void onResponse(Call c,Response response){try(Response close=response){String text=response.body()==null?"":response.body().string();JSONObject json=text.isEmpty()?new JSONObject():new JSONObject(text);if(!response.isSuccessful()){listener.onError(json.optString("error","request_failed"));return;}if(json.has("reconnect_token")){listener.onSession(json);connect(json.optString("room_code"),json.optString("reconnect_token"));}else listener.onState(json);}catch(Exception e){listener.onError("invalid_server_response");}}});}
 public void reconnect(String code,String token){closing=false;connect(code,token);}private void connect(String code,String token){closeSocket();Request request=new Request.Builder().url(base.replaceFirst("^http","ws")+"/ws/v1/ludo/"+code+"/?token="+token).build();socket=http.newWebSocket(request,new WebSocketListener(){public void onMessage(WebSocket ws,String text){try{JSONObject message=new JSONObject(text);if("state".equals(message.optString("type")))listener.onState(message.getJSONObject("payload"));else listener.onError(message.optString("error"));}catch(Exception e){listener.onError("invalid_server_response");}}public void onFailure(WebSocket ws,Throwable t,Response r){if(!closing)listener.onDisconnected();}public void onClosed(WebSocket ws,int c,String r){if(!closing)listener.onDisconnected();}});}
 public void roll(){if(socket!=null)socket.send("{\"type\":\"roll\"}");}public void move(int piece){if(socket!=null)socket.send("{\"type\":\"move\",\"piece\":"+piece+"}");}private void closeSocket(){if(socket!=null){socket.close(1000,"reconnecting");socket=null;}}public void disconnect(){closing=true;closeSocket();}
}
